### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gloomy-ghost** [gloomy-ghost/ew#1]
- [x] Check HSTS Preloading
- [ ] Check the difference between http and https
- [ ] Try to find test when `/` returns non-2xx code

**Comment by gloomy-ghost** [comment]
@ivysrono 最近啥都不想干……有空看看这个呗，正好是py流水账系列

**Comment by ivysrono** [comment]
Python 基本语法都没学完呢……

**Comment by gloomy-ghost** [comment]
现查现用啊，我这一坨if-else everywhere都放出来了（逃

**Comment by ivysrono** [comment]
嗯嗯，if - else 还是能看懂的~

**Comment by ivysrono** [comment]
如果gooreplacer作者这周不能解决在Firefox4android上的问题，我就搞个自制版httpsew~
这样就不用等着merge，主要是便于维护redirector里几十条规则……
